steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'asia-southeast1-docker.pkg.dev/deploy-next-app/next-app-docker/web-frontend:$SHORT_SHA',
        '.'
      ]

  # Step 2: Push image lên Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast1-docker.pkg.dev/deploy-next-app/next-app-docker/web-frontend:$SHORT_SHA'
      ]

# Optional: Đặt "latest" tag để dễ deploy (ngoài tag commit hash)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'tag',
        'asia-southeast1-docker.pkg.dev/deploy-next-app/next-app-docker/web-frontend:$SHORT_SHA',
        'asia-southeast1-docker.pkg.dev/deploy-next-app/next-app-docker/web-frontend:latest'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast1-docker.pkg.dev/deploy-next-app/next-app-docker/web-frontend:latest'
      ]

# Output image list (hiển thị trong log)
images:
  - 'asia-southeast1-docker.pkg.dev/deploy-next-app/next-app-docker/web-frontend:$SHORT_SHA'
  - 'asia-southeast1-docker.pkg.dev/deploy-next-app/next-app-docker/web-frontend:latest'
