steps:
  # 1. Build Docker image cho Next.js
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast1-docker.pkg.dev/$PROJECT_ID/next-app-docker/next-frontend:$COMMIT_SHA',
        '.'
      ]

  # 2. Push Docker image lên Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast1-docker.pkg.dev/$PROJECT_ID/next-app-docker/next-frontend:$COMMIT_SHA'
      ]

  # 3. Triển khai lên GKE (cập nhật image trong Deployment)
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set',
        'image',
        'deployment/nextjs-app-project',
        'web=asia-southeast1-docker.pkg.dev/$PROJECT_ID/next-app-docker/next-frontend:$COMMIT_SHA'
      ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'

# Cho phép dùng biến môi trường động
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

# Substitutions mặc định (nếu chạy thủ công)
substitutions:
  _REGION: 'asia-southeast1'
  _REPOSITORY: 'next-app-docker'
  _IMAGE: 'next-frontend'
