# =========================
# Deployment: chạy app Next.js
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app-project
  labels:
    app: nextjs-app-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-app-project
  template:
    metadata:
      labels:
        app: nextjs-app-project
    spec:
      containers:
        - name: nextjs-app-project
          image: asia-southeast1-docker.pkg.dev/deploy-next-app/next-app-docker/web-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20

---

# =========================
# Service: expose app qua port 80
# =========================
apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-project-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: nextjs-app-project
  ports:
    - name: http
      port: 80
      targetPort: 3000

---

# =========================
# ManagedCertificate: HTTPS cho domain
# =========================
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: nextjs-app-project-cert
spec:
  domains:
    - your-domain.com
    - www.your-domain.com

---

# =========================
# Ingress: routing + SSL
# =========================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-app-project-ing
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "nextjs-app-project-cert"
spec:
  type: LoadBalancer   # 👈 sửa dòng này
  selector:
    app: nextjs-app-project
  ports:
    - port: 80
      targetPort: 3000
